[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  links2004/WebSockets @ ^2.7.2
  bblanchon/ArduinoJson @ ^7.2.0
  olikraus/U8g2 @ ^2.35.0
