[platformio]
default_envs = esp32cam_n, esp32cam_s, esp32cam_e, esp32cam_w

[env]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
build_flags =
  -DCAMERA_MODEL_AI_THINKER
  -DCORE_DEBUG_LEVEL=0

[env:esp32cam_n]
build_flags = ${env.build_flags} -DCAM_DIRECTION=\"N\"

[env:esp32cam_s]
build_flags = ${env.build_flags} -DCAM_DIRECTION=\"S\"

[env:esp32cam_e]
build_flags = ${env.build_flags} -DCAM_DIRECTION=\"E\"

[env:esp32cam_w]
build_flags = ${env.build_flags} -DCAM_DIRECTION=\"W\"
